name: rco
channels:
  - pytorch
  - conda-forge
  - defaults
  - fastai
dependencies:
  - python=3.7
  - torchvision
  - cudatoolkit
  - pytorch
  - pylint
  - nltk
  - autopep8
  - pytest
  - gensim
  - notebook
  - rope
  - cufflinks-py
  - pandas
  - textblob
  - fastai
  - tensorboardx
  - pip
  - pip:
    - transformers
    - click
    - joblib
    - praw
    - prawcore
    - psaw
    - pyqt5-sip
    - pyqtwebengine
    - regex
    - sacremoses
    - sentencepiece
    - tokenizers
    - transformers

